# Generated by Django 5.2.8 on 2026-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_is_hidden_alert_priority_alert_reports_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='is_hidden',
            new_name='is_fake',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='reports_count',
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_authorities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='reports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], default='LOW', max_length=10),
        ),
        migrations.DeleteModel(
            name='AlertReport',
        ),
    ]
