# Generated by Django 5.2.8 on 2026-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_priority_alertreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertreport',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='alertreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('pending_review', 'Pendente'), ('forwarded', 'Encaminhado')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertreport',
            name='reason',
            field=models.TextField(),
        ),
    ]
