# Generated by Django 5.2.8 on 2026-06-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_rename_author_alertreport_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_notifications', to='alerts.alert')),
            ],
        ),
        migrations.DeleteModel(
            name='AlertReport',
        ),
    ]
