# Generated by Django 5.2.8 on 2026-06-19 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_authoritynotification_delete_alertreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confirmations',
            field=models.ManyToManyField(blank=True, related_name='confirmed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='false_reports',
            field=models.ManyToManyField(blank=True, related_name='false_reported_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
