# Generated by Django 5.2.8 on 2026-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alert_latitude_alert_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('in_resolution', 'Em resolução'), ('resolved', 'Resolvido'), ('false', 'Falso'), ('pending_review', 'Pendente de Revisão')], default='active', max_length=20),
        ),
    ]
