# Generated by Django 5.2.8 on 2026-06-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_alert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
