# Generated by Django 5.2.8 on 2026-06-20 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alert_is_anonymous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='alert',
            name='handled_by',
            field=models.ForeignKey(blank=True, help_text='A esquadra/autoridade que assumiu a ocorrência.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
