# Generated by Django 5.2.8 on 2026-06-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_user_bio_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authority',
            field=models.BooleanField(default=False, help_text='Designa se este utilizador é uma entidade de segurança.'),
        ),
        migrations.AddField(
            model_name='user',
            name='station_name',
            field=models.CharField(blank=True, help_text="Nome da esquadra, ex: 'Esquadra de Tchumene'.", max_length=150),
        ),
    ]
